### ISSUE TITLE
Roby:ExecutionEngine garbages free plan events

### ISSUE THREAD

**Issue by D-Alex** [rock-core/tools-roby#36]
Use Case (Roby without syskit plugin).
The following task will never succeed because the AndGenerator Event is garbage collected right a way removing task and task2 from the AndGenerator object.

    Robot.actions do 
      ... 
       def move(arg)
          task = MyTask.new
          task2 = MyTask2.new
          (task | task2)
       end
    end
       
My workaround is to remove https://github.com/rock-core/tools-roby/blob/master/lib/roby/execution_engine.rb#L1698 deleting all free events not belonging to a transaction. 

Some more debugging revealed that the AndGenerator event gets collected by discover_new_objects and added as free_event to the plan after calling add(object). Is this intended? Must all embedded events be added to the plan as free events if they are not TaskEvents? What would be a proper fix?

**Comment by doudou** [comment]
All plan objects must belong to the plan. So, yes, the events must be discovered and added to the free events. A free event should be marked as useful as soon as it is connected to a TaskEvent (your case).

(You're getting into parts of Roby that have seen little use in the last years ... Good !)

**Comment by doudou** [comment]
There's probably more to it than meets the eye ...

~~~
t1 = Roby::Task.new
t2 = Roby::Task.new
plan.add(t1 | t2)
assert plan.unneeded_events.empty?
~~~

passes on master

**Comment by D-Alex** [comment]
Actually, the test is not correct because in the error case the AndGenretor is added via a transaction. 
https://github.com/rock-core/tools-roby/blob/master/lib/roby/actions/task.rb#L86 using the action interface.

I am not sure that goes wrong but it seems that the transaction is adding the free event to the real plan but misses something so that the event gets deleted the next round.

**Comment by doudou** [comment]
> Actually, the test is not correct because in the error case the AndGenretor is added via a transaction. 

Good catch. The problem was in the registration of task events during transaction commit. It should be fixed on master now (by 8305fc7fffc9bbb5e90b493ed67645414d2a6c09)

**Comment by D-Alex** [comment]
Thx - this event registration & propagation is really a beast ;-). While debugging I found two spots were we probably could add some additional error checks.

  *  is that an error if all tasks are pending?
      https://github.com/rock-core/tools-roby/blob/master/lib/roby/execution_engine.rb#L1615  

  *  is that an error if a event is added which is not included in the set of useful_events
     https://github.com/rock-core/tools-roby/blob/master/lib/roby/plan.rb#L837

**Comment by doudou** [comment]
> is that an error if all tasks are pending?

No. It can happen if e.g. you create a plan that is waiting on an external event, and then decide to drop it because you don't need it anymore.

> is that an error if a event is added which is not included in the set of useful_events

Usefulness is a global property, adding task a local operation: most tasks and events are not useful when added. This will actually become the norm when I get the time to refactor the Roby graph code (something that is really really needed), because an object will have to be in a plan before it can be added to a relation graph.

The only place where such a check could be added is during transaction commit. I'm not sure it's that useful, though, since it would force every transaction-creation code to make sure they clean up before they commit (which would end up being something like running a garbage collector pass)
